### ISSUE TITLE
Verifica Shader

### ISSUE THREAD

**Issue by Enricodb95** [DIMA-UniversityOfUdine/product-visualization-dal-ben-enrico#1]
Ho caricato i file , le cubemap e i modelli.
All'interno del file freni.html troverà anche il codice per la point light, all'interno dello shader però è stato commentato quindi non dovrebbe influire sul risultato.

**Comment by robertoranon** [comment]
Salve,

  Non capisco su quale repository avrebbe caricato i file …



On 15 May 2017, at 16:58, Enricodb95 <notifications@github.com<mailto:notifications@github.com>> wrote:


Ho caricato i file , le cubemap e i modelli.
All'interno del file freni.html troverà anche il codice per la point light, all'interno dello shader però è stato commentato quindi non dovrebbe influire sul risultato.

**Comment by Enricodb95** [comment]
Scusi non mi lasciava caricare direttamente i file ma solo tramite una nuova branch.
Ora ho fatto il merge delle due e quindi può vedere i file.

**Comment by robertoranon** [comment]
Salve,

  Il problema non è nello shader, che è giusto, ma nel modo in cui carica il modello e assegna i materiali.
Provi a seguire la procedura che ho usato in vari esempi:

- un ciclo sui figli di group
- per ognuno, crea la mesh, assegnando il materiale, la trasforma, e la aggiunge alla scena.

Le riporto il frammento di codice senza il ciclo (cioè, viene caricato solo il primo oggetto:

var loader = new THREE.OBJLoader();
loader.load( "models/ninjaHead_Low.obj", function ( group ) {
geometry = group.children[ 0 ].geometry;
geometry.center();
mesh = new THREE.Mesh( geometry, ourMaterial );
mesh.scale.multiplyScalar( 0.1 );
scene.add( mesh );
} );

Mi faccia sapere se ci sono ancora problemi

RR


On 15 May 2017, at 16:58, Enricodb95 <notifications@github.com<mailto:notifications@github.com>> wrote:


Ho caricato i file , le cubemap e i modelli.
All'interno del file freni.html troverà anche il codice per la point light, all'interno dello shader però è stato commentato quindi non dovrebbe influire sul risultato.

**Comment by Enricodb95** [comment]
Scusi ho ricontrollato e era solo un problema di angolo di visualizzazione dell'oggetto in realtà rimane uguale e non aggiunge ne blur ne modifiche appariscenti che prima non ci fossero.
Può comunque guardare il risultato nel file freni.html.
